FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:edge
RUN curl -O https://download.java.net/openjdk/jdk7u75/ri/openjdk-7u75-b13-linux-x64-18_dec_2014.tar.gz
RUN tar -zxvf openjdk-7u75-b13-linux-x64-18_dec_2014.tar.gz
RUN mkdir -p /usr/lib/jvm
RUN mv java-se-7u75-ri /usr/lib/jvm/java-7-openjdk-amd64
RUN ls /usr/lib/jvm