FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge
RUN curl -O https://download.java.net/java/GA/jdk21.0.2/f2283984656d49d69e91c558476027ac/13/GPL/openjdk-21.0.2_linux-aarch64_bin.tar.gz
RUN tar -zxvf openjdk-21.0.2_linux-aarch64_bin.tar.gz
RUN mkdir -p /usr/lib/jvm
RUN mv jdk-21.0.2 /usr/lib/jvm/java-21-openjdk-arm64